Add boilerplate code
meshery/meshery-perf pull request #4
Opened 2022-02-07 14:25 UTC by navendu-pottekkat

**Description**

This PR fixes #3

- [ ] Initialised new component with MeshKit functions
- [ ] Update build scripts (Makefile)
- [ ] Create Dockerfile
- [ ] Create build and publish workflow

**Notes for Reviewers**

@Revolyssup , @utkarsh-pro Do we need to define CRDs in order to create components? The url for the manifest file is not created now. Could you guide on how to proceed from here?

- [ ] Yes, I signed my commits.

2022-02-11 08:48 UTC, Revolyssup requested changes

2022-02-11 08:48 UTC, Revolyssup commented on go.mod
> +module github.com/meshery/meshery-perf
We would not need this file. As far as I know, meshery perf will not register any definitions and schemas. So for that reason, this file is not needed. We are not registering any components here

2022-02-11 08:48 UTC, Revolyssup commented on main.go
> +	go registerCapabilities(service.Port, log)            //Registering static capabilities
I think these two go routines can be removed.

2022-02-11 08:48 UTC, Revolyssup commented on perf/oam/register.go
> +package oam
This file can be removed as well.

2022-03-07 19:55 UTC, leecalcote commented
@navendu-pottekkat ping me and I'll get you going.

2022-03-10 03:43 UTC, leecalcote commented
@navendu-pottekkat @hershd23 @gyohuangxin I have added/updated workflows, added dockerfile and makefile.

2022-03-10 03:44 UTC, leecalcote commented
Merging to unblock and enable progress...

2022-03-10 03:44 UTC, merged